Спринт №13
m3Rzy/java-shareit pull request #1
Opened 2023-09-27 20:42 UTC by m3Rzy

2023-09-28 20:28 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-09-28 20:28 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/handler/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
Можно объединить в один метод, перечислив классы в аннотации, найди как это реализовать...

2023-09-28 20:28 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/exception/OwnerNotFoundException.java
> +public class OwnerNotFoundException extends RuntimeException {
Не нужно писать `Owner...`, класс должен быть более общий, подходящий для любой сущности
`NotFoundException`
А сообщением ты детализируешь проблему.

2023-09-28 20:28 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    Optional<Item> findItemById(Long itemId);
Из сервиса уже не `Optional`
Не определенность может быть в базе данных, а в сервисе ты уже точно будешь знать есть объект или нет, и ты или его возвращаешь или кидаешь исключение.
Поэтому просто: `Item findById(Long itemId);`

2023-09-28 20:28 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    Optional<Item> createItem(Item item);
create, update могут быть `void` - они или выполнятся или упадут с ошибкой, которая будет перехвачена.

2023-09-28 20:28 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/storage/dao/ItemDao.java
> +    Optional<Item> add(Item item);
Optional только у `findById`

Давай в dao использовать глагол `find`, а в сервисах `get`

2023-09-28 20:28 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/user/exception/EmailBadRequestException.java
> +public class EmailBadRequestException extends RuntimeException {
Не конкретный класс, а более общий...

2023-09-29 19:31 UTC, m3Rzy commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    Optional<Item> createItem(Item item);
Почему нельзя просто возвращать объект или возвращать ошибку? Реализация методов будет ведь одинаковой

2023-09-30 06:06 UTC, FanaticFiz commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    Optional<Item> createItem(Item item);
Да, объект возвращать можно.
Но не оборачивай тогда в `Optional` - ты точно знаешь что объект есть.

2023-09-30 06:07 UTC, FanaticFiz approved these changes

2023-10-16 16:46 UTC, merged