Спринт №16
m3Rzy/java-shareit pull request #4
Opened 2023-10-30 19:01 UTC by m3Rzy

2023-10-31 19:47 UTC, m3Rzy commented
Разделил прогу на 2 микросервиса, но не понимаю почему с докером не проходят тесты в Postman, а именно /items & /bookings, до этого проходил те же тесты (15 спринт) и всё было норм, возможно, BaseClient или Client для Bookings и Items написан некорректно?

2023-11-01 19:24 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-11-01 19:24 UTC, FanaticFiz commented on pom.xml
> +	<modules>
В корневом pom теперь не должно быть зависимостей.
Ведь они все наследуются дочерними! И по-сути теперь дублируются, а еще и  присутствуют там где не должны.

![image](https://github.com/m3Rzy/java-shareit/assets/3994663/54d95bd7-79b1-486d-8a50-e35701ea4cf8)

2023-11-01 19:24 UTC, FanaticFiz commented on shareit-gateway/pom.xml
> +		<java.version>11</java.version>
Вот версия может быть указана один раз в родительском `pom`

2023-11-01 19:24 UTC, FanaticFiz commented on shareit-gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        BookingStatus.from(state)
Почему нам приходится это писать, почему не принимаем как enum?

`@RequestParam(defaultValue = "ALL") BookingStatus state,`

2023-11-01 19:24 UTC, FanaticFiz commented on shareit-server/src/main/resources/application.properties
> +server.port=9090
Почему бы не перевести в YAML формат?

2023-11-01 19:50 UTC, m3Rzy commented on shareit-gateway/src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        BookingStatus.from(state)
Так мы принимаем его как строку, затем преобразовываю его в Enum. Есть специальный метод, который это и делает from() - BookingStatus.java
Из-за этого может быть ошибка? Ранее такой параметр и был

2023-11-01 19:59 UTC, m3Rzy commented on shareit-server/src/main/resources/application.properties
> +server.port=9090
YAML просто сложнее, да и используется, когда структура сама по себе сложная, поэтому оставил .properties, чтобы в нём до конца уже разобраться, но если принципиально, то могу на YAML переписать. Так особо не встречал пока особой разницы между ними, разве что в YAML можно добавить списки, хэши и т.д для удобства построения иерархической структуры.

2023-11-01 20:19 UTC, m3Rzy commented
Поправил, но с тестами всё та же история

2023-11-02 18:38 UTC, FanaticFiz requested changes
Финальный комментарий на Я.Практикуме

2023-11-02 18:38 UTC, FanaticFiz commented on shareit-gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +    protected <T> ResponseEntity<Object> post(String path, Long userId, @Nullable Map<String, Object> parameters, T body) {
Ну вообще ты прав, без прохождения тестов работу и принять нельзя.
В первый раз я и не обратил на это внимание, многие студенты торопятся пораньше сдавать даже без тестов - горят по времени.

Базовый клиент у вас же есть из коробки?
Тут видно что местами `post(String path, Long userId, @Nullable Map<String, Object> parameters, T body) {`, parameters всегда `null`.
Но на глаз ничего криминального, да и порой лишний или не достающий слеш или пробел все ломает...

Так что смотри логи контейнера: `docker logs -f {container-name}`, при выполнении этих запросов.
Почему 500 ошибка, где именно падает.

2023-11-04 00:18 UTC, m3Rzy commented
Не понимаю ошибку 500 при создании все равно. Проверка на available есть, но он её как будто пропускает. (находится в классе BookingServiceImpl.java у метода create()) + запросы GET из Postman'a никак не лечатся вместе со временем, точно нет проблемы с файлом .json? Я посмотрел чужие репы, прогнал через postman и ошибки также есть в GET-запросах.

2023-11-04 00:22 UTC, m3Rzy commented
В остальном, вроде бы, исправлено успешно)

2023-11-04 21:18 UTC, FanaticFiz approved these changes

2023-11-05 18:31 UTC, merged